[package]
name = "jpg-convert"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.5"
indicatif = "0.17.2"
clap = { version = "4.0.32", features = ["derive"] }
